version: "2"
services:
  python:
    build: ./python
    container_name: test-python
    volumes:
      - ./workspace:/workspace
    tty: true
  dynamodb-local:
    build: ./dynamodb-local
    container_name: test-dynamodb-local
    tty: true